# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.5.1

pipelines:
  branches:
    master:
      - step:
          script: # Modify the commands below to build your repository.
            - BUILD_TIME=`date +%Y-%m-%dT%H:%M:%S%z`
            - REVISION=${BITBUCKET_COMMIT::4}
            - pip install "awscli>=1.11,<1.12" "Sphinx>=1.6,<1.7" "sphinx_rtd_theme>=0.2,<0.3"
            - cd docs/
            - make html
            - mv _build/html ../exam.yueh-cake.com/docs
            - cd ../exam.yueh-cake.com/
            - sed -i "s/\${BUILD_NUMBER}/${BITBUCKET_BUILD_NUMBER}/g" __version__.json
            - sed -i "s/\${REVISION}/${REVISION}/g" __version__.json
            - sed -i "s/\${BUILD_TIME}/${BUILD_TIME}/g" __version__.json
            - sed "s/\${BUILD_NUMBER}/${BITBUCKET_BUILD_NUMBER}/g" index.html > _index.html
            - sed "s/\${REVISION}/${REVISION}/g" _index.html > __index.html
            - sed "s/\${BUILD_TIME}/${BUILD_TIME}/g" __index.html > ___index.html
            - mv ___index.html index.html
            - rm -rf *_index.html
            - cd jobs.at.ho600/
            - sed "s/\${BUILD_NUMBER}/${BITBUCKET_BUILD_NUMBER}/g" index.html > _index.html
            - sed "s/\${REVISION}/${REVISION}/g" _index.html > __index.html
            - sed "s/\${BUILD_TIME}/${BUILD_TIME}/g" __index.html > ___index.html
            - mv ___index.html index.html
            - rm -rf *_index.html
            - cd ..
            - sed -i "s/{{ datetime }}/${BUILD_TIME}/g" pipeline-messages.json
            - sed -i "s/{{ commit_hash }}/${BITBUCKET_COMMIT}/g" pipeline-messages.json
            - aws s3 sync exam.yueh-cake.com s3://exam.yueh-cake.com
            - aws ses send-email --region us-west-2 --from service@ho600.com --destination file://pipeline-destination.json --message file://pipeline-messages.json
